/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/cap_version_11.gltf --transform -M -j 
Files: public/models/cap_version_11.gltf [44.39MB] > cap_version_11-transformed.glb [2.74MB] (94%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cap_version_11-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Retopo_Text.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Retopo_Text001.geometry} material={materials['Material.002']} position={[0, 0, 0.003]} />
      <mesh geometry={nodes.Retopo_Text002.geometry} material={materials['Material.002']} position={[0, 0, -0.002]} />
      <mesh geometry={nodes.gold001.geometry} material={materials.stribe} />
      <mesh geometry={nodes.silver.geometry} material={materials['stribe.001']} />
      <mesh geometry={nodes.gold.geometry} material={materials.stribe} />
      <mesh geometry={nodes.silver001.geometry} material={materials['line 1.001']} />
      <mesh geometry={nodes.black.geometry} material={materials['line 1.002']} />
      <mesh geometry={nodes.sloejfe.geometry} material={materials.sloejfe_m} />
      <mesh geometry={nodes.the_top_of_the_cap_.geometry} material={materials['outside white']} />
      <mesh geometry={nodes.the_middle_part_.geometry} material={materials['outside black']} />
      <mesh geometry={nodes.the_fornt_part.geometry} material={materials['outide black 1']} />
      <mesh geometry={nodes.the_white_inside.geometry} material={materials['inside white with fold']} />
      <mesh geometry={nodes.the_leather_part.geometry} material={materials['inside leather']} />
      <mesh geometry={nodes.the_top_inside.geometry} material={materials['inside white 1']} />
      <mesh geometry={nodes.the_line_in_the_bottom.geometry} material={materials['inside black']} />
      <mesh geometry={nodes.cap_line_1.geometry} material={materials['line 2']} />
      <group scale={0.071}>
        <mesh geometry={nodes.Plane003.geometry} material={materials.gold} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['diamond.001']} />
      </group>
      <mesh geometry={nodes.first_002.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Diamond001.geometry} material={materials['diamond.001']} />
      <mesh geometry={nodes.Diamond001_1.geometry} material={materials.gold} />
    </group>
  )
}

useGLTF.preload('/cap_version_11-transformed.glb')
