/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/cap_version_13.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cap_version_13.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.visorfrontLine.geometry} material={materials['line 2']} />
      <mesh geometry={nodes.roundRibbonribon_gliter_gold.geometry} material={materials.gliter_texture_gold} />
      <mesh geometry={nodes.roundRibbonribon_gliter_silver.geometry} material={materials['gliter_texture_.001']} />
      <mesh geometry={nodes.roundRibbonribon_velvet_GOLD.geometry} material={materials.velvet_texture_GOLD} />
      <mesh geometry={nodes.roundRibbonribon_velvet_silver.geometry} material={materials.velvet_texture_} />
      <mesh geometry={nodes.badgeclassic.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.embroideryTextleft.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.embroideryTextright.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.embroideryTextback.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.rusetti.geometry} material={materials.sloejfe_m} />
      <mesh geometry={nodes.cordblack.geometry} material={materials['line 1.002']} />
      <mesh geometry={nodes.cordgold.geometry} material={materials['Tape. gliter gold']} />
      <mesh geometry={nodes.cordsilver.geometry} material={materials['line 1.001']} />
      <mesh geometry={nodes.visor.geometry} material={materials['outide black 1']} />
      <mesh geometry={nodes.panta.geometry} material={materials['inside leather']} />
      <mesh geometry={nodes.pantabottom.geometry} material={materials['inside black']} />
      <mesh geometry={nodes.pantavelvetBlack.geometry} material={materials['outside black']} />
      <mesh geometry={nodes.blueWhite.geometry} material={materials['inside white 1']} />
      <mesh geometry={nodes.whiteVelvet.geometry} material={materials['outside white']} />
      <mesh geometry={nodes.insidewhite.geometry} material={materials['inside white with fold']} />
      <mesh geometry={nodes.badgestarcube.geometry} material={materials['diamond.001']} />
      <mesh geometry={nodes.badgestarcube_1.geometry} material={materials.gold} />
      <mesh geometry={nodes.badgecrystalcube.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.badgecrystalcube_1.geometry} material={materials['diamond.001']} />
    </group>
  )
}

useGLTF.preload('/cap_version_13.gltf')
