/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/cap_version_0.gltf
*/

import { useState } from "react";
import {
  useGLTF,
  Decal,
  Environment,
  RenderTexture,
  PerspectiveCamera,
  Text3D,
} from "@react-three/drei";
import { useCustomization } from "../contexts/Customization";
import * as THREE from "three";
function Ylioppilaslakki(props) {
  const { nodes, materials } = useGLTF("/models/cap_version_9.gltf");

  const texture = new THREE.TextureLoader().load("/texture.jpg");

  const { customization } = useCustomization();

  return (
    <group {...props} dispose={null}>
      {/* decorative ribbon */}
      <mesh
        geometry={nodes.gold001.geometry}
        material={materials.stribe}
        visible={customization.roundRibbonColor === "gold"}
      />
      <mesh
        geometry={nodes.silver.geometry}
        material={materials["stribe.001"]}
        visible={customization.roundRibbonColor === "silver"}
      />

      {/* cord */}
      <mesh
        geometry={nodes.gold.geometry}
        material={materials["line 1"]}
        visible={customization.cordColor === "gold"}
      />
      <mesh
        geometry={nodes.silver001.geometry}
        material={materials["line 1.001"]}
        visible={customization.cordColor === "silver"}
      />
      <mesh
        geometry={nodes.black.geometry}
        material={materials["line 1.002"]}
        visible={customization.cordColor === "black"}
      />

      <mesh geometry={nodes.sloejfe.geometry} material={materials.sloejfe_m} />
      <mesh
        geometry={nodes.the_top_of_the_cap_.geometry}
        material={materials["outside white"]}
      />
      <mesh
        geometry={nodes.the_middle_part_.geometry}
        material={materials["outside black"]}
      >
        <Decal position={[-0.391, 0.36, -0.46]} rotation={[0, 0, 0]} scale={3}>
          <meshStandardMaterial
            roughness={0.1}
            transparent
            polygonOffset
            polygonOffsetFactor={-10}
            position={[0, -10, 1]}
          >
            <RenderTexture attach='map'>
              <PerspectiveCamera
                makeDefault
                manual
                position={[0, 0, 150]}
                rotation={[0, 0, -3.14]}
              />
              <ambientLight intensity={0.9} />
              <Environment preset='city' />
              <Text3D
                rotation={[3.0099999999999967, -2.68, -0.029999999999999166]}
                size={2}
                scale={[1, 1.5, 1]}
                height={0.15}
                font={"/Fonts/textType2.json"}
                position={[-0.600000000000002, 1.3000000000000012, 0]}
              >
                <meshPhysicalMaterial
                  attach='material'
                  metalness={0.1}
                  roughness={1}
                  color={customization.textColor}
                  map={texture}
                />
                {customization.embroideryTextFront.left}
              </Text3D>
              <Text3D
                rotation={[3.0099999999999967, -2.68, -0.1199999999999992]}
                size={2}
                scale={[1, 1.5, 1]}
                height={0.15}
                font={"/Fonts/textType2.json"}
                position={[-25, 0.9000000000000008, -0.46]}
              >
                <meshPhysicalMaterial
                  attach='material'
                  metalness={0.1}
                  roughness={1}
                  color={customization.textColor}
                  map={texture}
                />
                {customization.embroideryTextFront.right}
              </Text3D>
            </RenderTexture>
          </meshStandardMaterial>
        </Decal>

        <Decal position={[-0.391, 0.36, -0.46]} rotation={[0, 0, 0]} scale={3}>
          <meshStandardMaterial
            roughness={0.1}
            transparent
            polygonOffset
            polygonOffsetFactor={-10}
            position={[0, -10, 1]}
          >
            <RenderTexture attach='map'>
              <PerspectiveCamera makeDefault manual position={[0, 0, 150]} />
              <ambientLight intensity={0.9} />
              <Environment preset='city' />

              <Text3D
                rotation={[0, -3.800000000000001, -0.04000000000000003]}
                size={3}
                height={0.3}
                font={"/Fonts/textType2.json"}
                position={[25.909000000000173, -11.239999999999993, -0.46]}
                color='black'
              >
                <meshPhysicalMaterial
                  attach='material'
                  metalness={0.1}
                  roughness={1}
                  color={customization.textColor}
                  map={texture}
                />
                {customization.embroideryTextBack}
              </Text3D>
            </RenderTexture>
          </meshStandardMaterial>
        </Decal>
      </mesh>
      <mesh
        geometry={nodes.the_fornt_part.geometry}
        material={materials["outide black 1"]}
      />
      <mesh
        geometry={nodes.the_white_inside.geometry}
        material={materials["inside white with fold"]}
      />
      <mesh
        geometry={nodes.the_leather_part.geometry}
        material={materials["inside leather"]}
      />
      <mesh
        geometry={nodes.the_top_inside.geometry}
        material={materials["inside white 1"]}
      />
      <mesh
        geometry={nodes.the_line_in_the_bottom.geometry}
        material={materials["inside black"]}
      />
      <mesh
        geometry={nodes.cap_line_1.geometry}
        material={materials["line 2"]}
      />

      {/* crystal */}
      <group scale={0.071} visible={customization.badge === "crystal"}>
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane003_1.geometry}
          material={materials["diamond.001"]}
        />
      </group>

      {/* suomi */}
      <mesh
        geometry={nodes.first_002.geometry}
        material={materials["Material.005"]}
        visible={customization.badge === "fi"}
      />

      {/* start */}
      <mesh
        geometry={nodes.Diamond001.geometry}
        material={materials["diamond.001"]}
        visible={customization.badge === "star"}
      />
      <mesh
        geometry={nodes.Diamond001_1.geometry}
        material={materials.gold}
        visible={customization.badge === "star"}
      />
    </group>
  );
}

export default Ylioppilaslakki;

useGLTF.preload("./models/cap_version_9.gltf");
