/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/cap_version_0.gltf
*/

import { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCustomization } from "../contexts/Customization";


function Ylioppilaslakki(props) {
  const textMeshRef = useRef();

  const { nodes, materials } = useGLTF('./models/cap_version_0.gltf')
  //const { badge, legs, roundRibbonColor, cordColor } = useCustomization();
  const { badge } = useCustomization();
 

  

     
  useEffect(() => {
    // The GLTF model has finished loading here, so the textMeshRef should be set properly
    if (textMeshRef.current) {
      //console.log('Text mesh exists and is ready!');
      // Now you can call changeText or do any other operations with the textMeshRef.current
      changeText();
    }
  }, [textMeshRef]);

  const changeText = () => {
    console.log(textMeshRef.current); // Check the value in the console
    if (textMeshRef.current) {
      console.log('yes');
      //textMeshRef.current.geometry.setText('Nice'); // Replace 'New Text' with your desired text
    } else {
      console.log('Text mesh not available yet');
    }
  };

  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.648, 0]} rotation={[Math.PI / 2, 0, 0]}>

        <mesh geometry={nodes.betraek.geometry} material={materials.betraek_m} />
        <mesh geometry={nodes.betraekbaand_h.geometry} material={materials.snor_med_bump_m} position={[0, 0, -1.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.farvebaand.geometry} material={materials.farvebaand_m} scale={[0.999, 0.999, 1]} />
        <mesh geometry={nodes.filtbaand.geometry} material={materials.filtbaand_m} position={[0, 0.176, 1.132]} rotation={[-0.16, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.foer.geometry} material={materials.foer_m} position={[0, 0, 0.833]} scale={0.01} />
        <mesh geometry={nodes.nakke_striber.geometry} material={materials.kant_striber_m} position={[0, -3.102, 0.447]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.skygge.geometry} material={materials.skygge_m} position={[0.004, 3.057, 0.515]} rotation={[-0.771, 0, 0]} scale={[0.01, 0.01, 0.009]} />
        <mesh geometry={nodes.skygge_underside.geometry} material={materials.skygge_m} position={[0.004, 3.058, 0.515]} rotation={[-0.771, 0, 0]} scale={[0.01, 0.01, 0.009]} />
        <mesh geometry={nodes.svedbaand.geometry} material={materials.svedbaand_m} position={[0, 0, 0.808]} scale={0.01} />
      </group>

      <group position={[0, 1.648, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.kristallblomma_2.geometry} material={materials.kristalblomma_m} position={[0.034, 3.189, 0.363]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} visible={false}/>
        <mesh geometry={nodes.skyggebaand.geometry} material={materials.skyggebaand_m} position={[0, 0.014, 0.337]} rotation={[-1.731, 0, 0]} />
        <mesh geometry={nodes.sloejfe.geometry} material={materials.sloejfe_m} position={[0.072, -3.031, 0.433]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} />

        <mesh geometry={nodes.stribe.geometry} material={materials.stribe_m} position={[0, 0, -0.021]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.005, 0.75, 1.005]} 
       
          >
        
        </mesh>


      </group>


      <mesh geometry={nodes.Text.geometry} material={materials['Material.006']} position={[0, 0, 0.01]} ref={textMeshRef}  />

      
      <group position={[0.011, 1.402, 3.258]} rotation={[1.41, 0, 0]} scale={0.068} visible={badge === "crystal"}  >
        <mesh geometry={nodes.Plane002.geometry} material={materials['Material.002']}  />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.001']} />
      </group>

      <mesh geometry={nodes.first_002.geometry} material={materials['Material.003']} position={[0, -0.057, 0.006]} visible={badge === "suomi"}/>
      
      <group position={[0, 0, 6.659]} visible={badge === "star"} >
        <mesh geometry={nodes.Diamond001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Diamond001_2.geometry} material={materials['Material.005']} />
      </group>

      
    </group>
  )
}

export default Ylioppilaslakki;


useGLTF.preload('./models/cap_version_0.gltf')
