/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 --exec node ./readPackage.js public/models/yolakki1.gltf
*/

//import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

const Yolakki3D = (props) => {
  const { nodes, materials } = useGLTF('./models/yolakki1.gltf')

  const leatherTextureProps = useTexture({
    map: "./textures/leather/Leather_008_Base Color.jpg",
    normalMap: "./textures/leather/Leather_008_Normal.jpg",
    roughnessMap: "./textures/leather/Leather_008_Roughness.jpg",
    aoMap: "./textures/leather/Leather_008_Ambient Occlusion.jpg", 
  });

  const fabricTextureProps = useTexture({
    map: "./textures/fabric/Fabric_Knitted_006_basecolor.jpg",
    normalMap: "./textures/fabric/Fabric_Knitted_006_normal.jpg",
    roughnessMap: "./textures/fabric/Fabric_Knitted_006_roughness.jpg",
    aoMap: "./textures/fabric/Fabric_Knitted_006_ambientOcclusion.jpg",
  });

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.betraek.geometry} material={materials.betraek_m} position={[0, 0, 0.833]} scale={0.01} >
          <meshStandardMaterial {...fabricTextureProps}/>
        </mesh>
        <mesh geometry={nodes.betraekbaand_h.geometry} material={materials['snor_med_bump_m.001']} position={[0, 0, -1.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.farvebaand.geometry} material={materials.farvebaand_m} scale={[0.999, 0.999, 1]} />
        <mesh geometry={nodes.filtbaand.geometry} material={materials.filtbaand_m} position={[0, 0.025, 0.808]} scale={0.01} />
        <mesh geometry={nodes.foer.geometry} material={materials.foer_m} position={[0, 0, 0.833]} scale={0.01} />
        <mesh geometry={nodes.kokade.geometry} material={materials.kokade_m} position={[0.031, 3.126, 0.363]} rotation={[-Math.PI / 2, 0.015, 0]} scale={0.007} />
        <mesh geometry={nodes.kronebroderi.geometry} material={materials.kronebroderi_m} position={[0, 0, -1.41]} rotation={[0, 0, -Math.PI]} scale={0.01} />
        <mesh geometry={nodes.nakke_striber.geometry} material={materials.kant_striber_m} position={[0, -3.102, 0.447]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.navn_l.geometry} material={materials['material #25_l_m']} position={[0, 0, 0.833]} scale={0.01} />
        <mesh geometry={nodes.navn_r.geometry} material={materials['material #25_l_m']} position={[0, 0, 0.833]} scale={0.01} />
        <mesh geometry={nodes.navnbaand001.geometry} material={materials['material #25_l_m']} position={[0, 0, 0.833]} rotation={[0, 0, Math.PI]} scale={0.01} />
        <mesh geometry={nodes.roset_h.geometry} material={materials.roset_m} position={[0, 3.119, 0.362]} rotation={[-Math.PI / 2, 0, 0]} scale={0.007} />

        <mesh geometry={nodes.skygge.geometry} material={materials.skygge_m} position={[0.004, 2.969, 0.658]} rotation={[-0.611, 0, 0]} scale={[0.01, 0.01, 0.009]}>
          <meshStandardMaterial {...leatherTextureProps}/>
        </mesh>

        <mesh geometry={nodes.skygge_underside.geometry} material={materials.skygge_m} position={[0.004, 2.969, 0.658]} rotation={[-0.611, 0, 0]} scale={[0.01, 0.01, 0.009]} />
        <mesh geometry={nodes.sloejfe_h.geometry} material={materials.sloejfe_m} position={[0, -2.968, 0.31]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh geometry={nodes.svedbaand.geometry} material={materials.svedbaand_m} position={[0, 0, 0.808]} scale={0.01} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.flaglogo.geometry} material={materials.skolelogo_m} position={[0, 2.152, -0.35]} scale={0.7} />
        <mesh geometry={nodes.skolelogo.geometry} material={materials.skolelogo_m} position={[0, -1.87, 0]} />
        <mesh geometry={nodes.kristallblomma_2.geometry} material={materials.kristalblomma_m} position={[0.034, 3.189, 0.363]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} />
        <mesh geometry={nodes.navnbaand.geometry} material={materials.navnbaand_m} />
        <mesh geometry={nodes.skolebroderi.geometry} material={materials.skolebroderi_m} position={[0, -0.023, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.093, 1, 1]} />
        <mesh geometry={nodes.skyggebaand.geometry} material={materials.skyggebaand_m} position={[0, -0.007, -0.003]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.sloejfe.geometry} material={materials.sloejfe_m} position={[0.072, -3.031, 0.433]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} />
        <mesh geometry={nodes.stribe.geometry} material={materials.stribe_m} position={[0, 0, -0.021]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.005, 0.75, 1.005]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/yolakki1.gltf')

export default Yolakki3D;
